"""Add Google Calendar fields

Revision ID: 3b773858df1a
Revises: 
Create Date: 2025-12-03 13:43:49.422519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b773858df1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('google_event_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_credentials', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_credentials')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('google_event_id')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
